first steps rest assured
dairoquintero/project_api_test pull request #3
Opened 2021-05-10 17:54 UTC by dairoquintero

2021-05-10 19:46 UTC, aperdomob requested changes
you missed add test for HEAD

2021-05-10 19:46 UTC, aperdomob commented on src/test/java/co/com/api/test/PageBase.java
> +package co.com.api.test;
this file is not needed, please remove and add into your test the content

2021-05-10 19:54 UTC, dairoquintero reviewed
Done

2021-05-11 12:26 UTC, aperdomob approved these changes

2021-05-11 12:26 UTC, merged